'use strict';
const { Model } = require('sequelize');

// Type Royale Word Bank Model - Spell Word Storage
module.exports = (sequelize, DataTypes) => {
  class WordBank extends Model {
    static associate(models) {
      // Associations will be defined in index.js  
    }
  }

  WordBank.init({
  id: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true
  },
  topic: {
    type: DataTypes.STRING(100),
    allowNull: false,
    comment: 'Topic for spell word generation (e.g., magic, fantasy, elemental)'
  },
  spell_type: {
    type: DataTypes.ENUM('easy_fireball', 'medium_fireball', 'hard_fireball', 'shield'),
    allowNull: false,
    comment: 'Type of spell card these words are for'
  },
  difficulty_level: {
    type: DataTypes.ENUM('easy', 'medium', 'hard', 'shield'),
    allowNull: false,
    comment: 'Word difficulty for typing challenge'
  },
  words: {
    type: DataTypes.JSON, // Use JSON for PostgreSQL
    allowNull: false,
    comment: 'Array of words generated by AI for this spell type'
  },
  word_count: {
    type: DataTypes.INTEGER,
    defaultValue: 0,
    comment: 'Number of words in this word bank'
  },
  
  // AI Generation Info
  ai_model: {
    type: DataTypes.STRING(50),
    defaultValue: 'gemini-pro',
    comment: 'AI model used to generate words'
  },
  prompt_used: {
    type: DataTypes.TEXT,
    allowNull: true,
    comment: 'The prompt sent to AI to generate these words'
  },
  generated_by_ai: {
    type: DataTypes.BOOLEAN,
    defaultValue: true
  },
  
  // Game Mechanics
  damage_value: {
    type: DataTypes.INTEGER,
    defaultValue: 0,
    comment: 'HP damage this spell type deals'
  },
  spell_speed: {
    type: DataTypes.ENUM('fast', 'normal', 'slow', 'instant'),
    defaultValue: 'normal',
    comment: 'Speed of spell projectile'
  },
  
  // Usage Statistics  
  usage_count: {
    type: DataTypes.INTEGER,
    defaultValue: 0,
    comment: 'How many times this word bank has been used in games'
  },
  last_used_at: {
    type: DataTypes.DATE,
    allowNull: true
  },
  
  // Status
  is_active: {
    type: DataTypes.BOOLEAN,
    defaultValue: true
  }
}, {
  sequelize,
  modelName: 'WordBank',
  tableName: 'word_banks',
  timestamps: true,
  underscored: true,
  indexes: [
    { fields: ['topic', 'spell_type', 'difficulty_level'] },
    { fields: ['spell_type'] },
    { fields: ['difficulty_level'] },
    { fields: ['is_active'] },
    { fields: ['topic'] }
  ]
});

// Instance methods
WordBank.prototype.getRandomWords = function(count = 10) {
  const words = this.words;
  if (!Array.isArray(words) || words.length === 0) {
    return [];
  }
  
  // Shuffle and return requested count
  const shuffled = [...words].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, Math.min(count, shuffled.length));
};

WordBank.prototype.getRandomWord = function() {
  const words = this.getRandomWords(1);
  return words.length > 0 ? {
    word: words[0],
    spell_type: this.spell_type,
    difficulty: this.difficulty_level,
    damage: this.damage_value,
    speed: this.spell_speed
  } : null;
};

WordBank.prototype.incrementUsage = async function() {
  this.usage_count += 1;
  this.last_used_at = new Date();
  await this.save();
};

// Static methods
WordBank.getSpellDamage = function(spellType) {
  const damageMap = {
    'easy_fireball': 10,
    'medium_fireball': 30,
    'hard_fireball': 80,
    'shield': 0
  };
  return damageMap[spellType] || 10;
};

WordBank.getSpellSpeed = function(spellType) {
  const speedMap = {
    'easy_fireball': 'fast',
    'medium_fireball': 'normal', 
    'hard_fireball': 'slow',
    'shield': 'instant'
  };
  return speedMap[spellType] || 'normal';
};

WordBank.getWordCountByType = function(spellType) {
  const countMap = {
    'easy_fireball': 15,
    'medium_fireball': 15,
    'hard_fireball': 15,
    'shield': 5
  };
  return countMap[spellType] || 10;
};

  return WordBank;
};